---
apiVersion: v1
kind: Service
metadata:
  name: overtype-service
  namespace: personal
  labels:
    app: overtype
spec:
  selector:
    app: overtype
  ports:
    - port: 8080
      name: overtype-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overtype-deployment
  namespace: personal
  labels:
    app: overtype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overtype
  template:
    metadata:
      labels:
        app: overtype
    spec:
      imagePullSecrets:
        - name: github-container-registry
      containers:
        - name: overtype
          imagePullPolicy: Always
          image: ghcr.io/envycode/overtype:${{CHECKOUT}}
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: APP_NAME
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: APP_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: APP_PORT
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: APP_ENV
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: DB_URI
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: overtype-config
                  key: REDIS_HOST
      volumes:
        - name: overtype-config
          configMap:
            name: overtype-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overtype-ingress
  namespace: personal
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: overtype.weeb.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overtype-service
                port:
                  number: 8080
