name: build_and_push_registry

on:
  workflow_dispatch:
    inputs:
      checkout:
        description: "Branch or Commit ID to build"
        default: "master"
        required: true
      backend_url:
        description: "Backend URL"
        default: "https://overtype.weeb.work"
        required: true
      ws_url:
        description: "WS URL"
        default: "wss://overtype.weeb.work"
        required: true

jobs:
  build_and_push_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git checkout ${{ github.event.inputs.checkout }}
      - run: cp web/.env.example web/.env
      - run: sed -i "s|{{WEB_SOCKET_BASE_URL}}|${{ github.event.inputs.ws_url }}|g" web/.env
      - run: sed -i "s|{{BASE_URL}}|${{ github.event.inputs.backend_url }}|g" web/.env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/envycode/overtype:${{ github.event.inputs.checkout }}
