name: deploy_to_remote_server

on:
  workflow_dispatch:
    inputs:
      checkout:
        description: "Branch or Commit ID to build"
        default: "master"
        required: true

jobs:
  deploy_to_remote_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git checkout ${{ github.event.inputs.checkout }}
      - run: sed -i "s/<CHECKOUT>/${{ github.event.inputs.checkout }}/g" .manifest/deployment.yaml
      - name: Pre check changes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: get pods -n personal -l app=overtype
      - name: Deploy changes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: apply -f .manifest/deployment.yaml -n personal
      - name: Post check changes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: get pods -n personal -l app=overtype
